kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: formatting check
    image: crystallang/crystal:latest-alpine
    commands:
      - crystal tool format --check
  - name: lint
    image: crystallang/crystal:latest-alpine
    commands:
      - shards install
      - bin/ameba
  - name: build
    image: crystallang/crystal:latest
    volumes:
      - name: cache
        path: /root/.cache
    commands:
      - apt-get update && apt-get install -y curl g++ webkit2gtk-4.0-dev make
      - shards install
      - make

volumes:
  - name: cache
    temp: {}
